### ISSUE TITLE
testcase result in Stackoverflow (infinite recursion)

### ISSUE THREAD

**Issue by Hellio404** [marcin-chwedczuk/reng#1]
I was trying to reimplement a regex matcher using the method you wrote about in the article but I found a test case that result in infinite recursion and I was wondering if you have a solution for it

the testcase: (a*|b)+

**Comment by marcin-chwedczuk** [comment]
I did not check the code, but I see what may be the reason for this bug.

While iterating `+` operator to match as much input as possible, we may come to a place where we match repeatedly empty string (from `a*` expression). In that case we should stop iterating `+` operator and move on to the next step of the algorithm.

The fix would be as follows:
* For operators like `X*` and `X+` if X resulted in match to an empty string `""` we should stop iteration, as any further iteration will result in the same match (empty string again).

Thanks for reporting @Hellio404 I will fix it in my free time. I hope the explanation is clear enough to allow you to finish your regex matcher.

**Comment by Hellio404** [comment]
Yes Exactly!

My solution for this was to add a new Input variable (prev_input) as an argument for repeatRec and whenever matchCount > 0 && prev_input == input it will return cont.run()

Thank you so much for the article it was very helpful

**Comment by marcin-chwedczuk** [comment]
OK fixed: https://github.com/marcin-chwedczuk/reng/commit/4f6fb73da2e05478d39af056f4a56f291f4d40ac
